### ISSUE TITLE
Flutter pocketbase db 501 error

### ISSUE THREAD

**Issue by timesignature** [pocketbase/dart-sdk#43] opened 2023-07-09 08:38 UTC
Hi
Pocketbase is not working as intended with flutter and the error I'm getting has a status code of 501. Sometimes it connects and sometimes it doesn't I don't know what's wrong with the package

**Comment by ganigeorgiev** [comment] 2023-07-09 08:44
I don't think this is related to PocketBase as API doesn't return 50x errors (or at least not directly).

Do you have a reverse proxy? Could you provide some more details about your setup or at least some reproducible steps?

**Comment by ganigeorgiev** [comment] 2023-07-09 09:00
I've just tested on Dart cli and Flutter Desktop and in both cases it is working fine for me, using the example code from [example/example.dart](https://github.com/pocketbase/dart-sdk/blob/master/example/example.dart).

Also, if you are testing with Flutter Web, please check https://github.com/pocketbase/dart-sdk#limitations.

I'll close the issue for now as there are not enough details, but if you are still not able to resolve it, please:
- Make sure that the PocketBase server is accessible from your device (_eg. you can't use localhost as the localhost of the device will be different from the localhost of the server_).
- Provide more information about your environment (where it is deployed, do you have a reverse proxy, etc.).
- Provide more information what platform you are targeting and how you are testing.

**Closed by ganigeorgiev** 2023-07-09 09:00 UTC

**Comment by timesignature** [comment] 2023-07-09 09:22
Hi
it's still on localhost. I'm getting this error on Android using
http://10.0.2.2:8090

**Comment by ganigeorgiev** [comment] 2023-07-09 09:31
@timesignature Are you testing with an emulator or a real device? Are they connected to the same network? There is really not enough information to help you debug it.

Make sure that the PocketBase server is accessible from the environment where you are testing. The easiest way to do that is to copy the initialization url that you use in the SDK initialization and open it in a browser on the device with `/_/` suffix to see if you can access the dashboard. If you are not able to access the PocketBase dashboard on the device, then there is something wrong with your local network setup, but again I'm not sure I can help you with the limited information you've provided.

**Comment by timesignature** [comment] 2023-07-09 09:35
I'm using Android emulator to run the app. Let me forward you the error I'm
getting

**Comment by timesignature** [comment] 2023-07-09 09:43
Expecting binder but got null!
I/flutter ( 4629): ClientException: {url:
http://10.0.2.2:8090/api/collections/todos/records?page=1&perPage=200,
isAbort: true, statusCode: 0, response: {}, originalError: Connection reset
by peer}

**Comment by ganigeorgiev** [comment] 2023-07-09 09:49
Sorry, I don't think I can help you. The above seems to be a client-side error and not PocketBase related.

Again, if you need further help, please provide detailed answers to the questions in the previous comments.

**Comment by timesignature** [comment] 2023-07-09 10:29
Hi
The error is related to pocketbase flutter package

**Comment by ganigeorgiev** [comment] 2023-07-09 10:35
@timesignature The above error has a status code `0`, meaning that it is a client-side error and the request never made it to the server. You can google for "Connection reset
by peer" and search for the various reason why the above error could be returned.

I'm sorry but I don't know how to help you further. You refuse to provide reproducible steps or even answers to my previous questions.

**Comment by timesignature** [comment] 2023-07-09 10:38
ClientException: {url:
http://10.0.2.2:8090/api/collections/todos/records?page=1&perPage=200,
isAbort: false, statusCode: 501, response: {}, originalError: null}

**Comment by timesignature** [comment] 2023-07-09 10:38
Tell me exactly what you need and i will give you

**Comment by timesignature** [comment] 2023-07-09 10:41
My Statement is this error is associated with pocketbase flutter package
not pocketbase server itself

**Comment by ganigeorgiev** [comment] 2023-07-09 10:43
We can argue the entire day, but you refuse to read the previous comments.

Please provide the following information:

1. Can you access `http://10.0.2.2:8090/_/` from the device browser?

2. What version of the PocketBase Dart SDK and executable you are using?

3. On what OS you are testing?

4. Do you have a reverse proxy, firewall, etc. in place?

5. To rule out PocketBase Dart SDK issue, try to send a regular GET request using the [dart-lang/http](https://github.com/dart-lang/http) package

6. Could you provide a reproducible code how you are making the request?

**Comment by timesignature** [comment] 2023-07-09 10:49
1.

   Can you access http://10.0.2.2:8090/_/ from the device browser? - yes i
   can access the url on my emulator
   2.

   What version of the PocketBase Dart SDK and executable you are using? -
   its version pocketbase: ^0.10.3
   3.

   On what OS you are testing? : Im using android emulator
   4.

   Do you have a reverse proxy, firewall, etc. in place? - i dont have a
   reverse proxy or a firewall
   5.

   To rule out PocketBase Dart SDK issue, try to send a regular GET request
   using the dart-lang/http <https://github.com/dart-lang/http> package -
   okay will try that
   6.

   Could you provide a reproducible code how you are making the request? -
   7.

   final pb=PocketBase("http://10.0.2.2:8090");
   final box = GetStorage();


   getTodo() async{
     try{
       final result = await pb.collection('todos').getFullList();
       print(result);
       return result;
     }catch(e){
       print(e.toString());
     }
   }

**Comment by timesignature** [comment] 2023-07-11 15:08
Hi did you check what is wrong with flutter pocketbase client ?

**Comment by timesignature** [comment] 2023-07-11 15:23
Thanks for trying!
